spring.application.name=One2N_SRE_Bootcamp
server.port=8085

# H2 Database Configuration
spring.datasource.driverClassName=org.h2.Driver
# Read configurations from system Environment Variables with a fallback default value
spring.datasource.url=${DB_URL:jdbc:h2:mem:studentdb}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Console to view tables via browser
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=true


