CREATE TABLE student (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         first_name VARCHAR(255) NOT NULL,
                         last_name VARCHAR(255) NOT NULL,
                         email VARCHAR(255) NOT NULL UNIQUE,
                         CONSTRAINT pk_student PRIMARY KEY (id)
);
